### PR TITLE
added summaries for alert messages and bumped version

### PR DESCRIPTION
**Pull request by robbanp**
I've added "Backlog Summary" items for each message in the alert.
screen shot 2016-07-30 at 0 43 30

### CODE REVIEW

**Comment by infernix** [comment]
> Please limit your messages to contain no more than 20 attachments to provide the best user experience. Whenever possible, we'll throw a too_many_attachments error when attempting to include more than 100 attachments. When using incoming webhooks, you'll receive that error as a HTTP 400.

This could be problematic with large backlogs. Perhaps it would be better to merge all messages into one single attachment?

**Comment by robbanp** [comment]
Yes, attachment, or if you can specify the number of items to show in the settings?
This is also something you can control in the alarm. I have the settings to send 5 items, but of course this can differ.

**Comment by robbanp** [comment]
Ok @infernix I created a setting for the backlog items.

**Comment by infernix** [comment]
This is definitely an improvement, thanks! 

However, if the Slack API will throw an error at more than 100 attachments, there can still be cases where the backlog is larger than that. 

So if all of the backlog is to be sent and it is over 100 messages, I would still think combining all messages into one single attachment would be better?

**Comment by robbanp** [comment]
Do you mean send it as I do now, but aggregated into one entry?

**Comment by infernix** [comment]
Yes, instead of one message.addAttachment for each backlog_item, consolidate all backlog_items in one single message.addAttachment. That way you wouldn't ever hit the attachment limit.

**Comment by robbanp** [comment]
Alright, its updated!

**Comment by infernix** [comment]
Looks great :+1:

**Comment by ramondelafuente** [comment]
This is a sorely needed feature, any chance of it being shipped soon?

**Comment by joschi** [comment]
@robbanp Could you please sign the CLA at https://cla-assistant.io/Graylog2/graylog-plugin-slack?pullRequest=26, so we can merge this PR?

**Comment by robbanp** [comment]
Done

**Comment by joschi** [comment]
@robbanp Thanks!

**Comment by ramondelafuente** [comment]
Cool! Good job :-)

Is there a way to get hold of a new build? (I don't java much)

**Comment by joschi** [comment]
@ramondelafuente You can clone this repo and build the latest `master` branch yourself.

Other than that, we're waiting a little bit longer to possibly include some other features into the new release.

**Comment by joschi** [comment]
@robbanp This PR is included in version 2.3.0 of this plugin.

**Comment by robbanp** [comment]
Awesome!

**Pull request merged**
