### PR TITLE
Features/proxy support

### PR DESCRIPTION
**Pull request by simonknoll**
I've implemented a simple proxy support for the slack plugin, so that the Slack webhook_url can be accessed behind a proxy.

### CODE REVIEW

**Comment by joschi** [comment]
@simonknoll Thank you for your contribution.

One question though: Why are you creating new configuration settings for the Slack plugin instead of using the existing [`http_proxy`](https://github.com/Graylog2/graylog2-server/blob/2.0.3/misc/graylog.conf#L432-L433) setting?

**Comment by simonknoll** [comment]
Hello @joschi thanks for responding!

You mean that the plugin extension should directly use the proxy defined in `http_proxy_uri`?
I didn't want to proxy the whole Graylog application but just the slack plugin.

**Comment by joschi** [comment]
@simonknoll Could you please sign the CLA at https://cla-assistant.io/Graylog2/graylog-plugin-slack?pullRequest=26, so we can merge this PR?

**Comment by joschi** [comment]
Thanks!

**Comment by Dougoc** [comment]
Thank @simonknoll ! Best feature.

**Pull request merged**
